import time
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setup(18,GPIO.OUT)
SP = [12,16,20,21]
SPP = [6,22,27,17]
SPPP = [1,7,8,6]

GPIO.setwarnings(False)

for pin in SP:
import time
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setup(18,GPIO.OUT)
SP = [12,16,20,21]
SPP = [6,22,27,17]
SPPP = [1,7,8,6]

GPIO.setwarnings(False)

for pin in SP:
GPIO.setup(pin,GPIO.OUT)
GPIO.output(pin, False)

for pin in SPP:
GPIO.setup(pin,GPIO.OUT)
GPIO.output(pin, False)

for pin in SPPP:
GPIO.setup(pin,GPIO.OUT)
GPIO.output(pin,False)

GPIO.output(18,True)
time.sleep(5)
GPIO.output(18,False)

for i in range(128):
GPIO.output(SP[0], False)
GPIO.output(SP[1], False)
GPIO.output(SP[2], False)
GPIO.output(SP[3], True)
time.sleep(0.01)
GPIO.output(SP[0], False)
GPIO.output(SP[1], False)
GPIO.output(SP[2], True)
GPIO.output(SP[3], True)
time.sleep(0.001)
GPIO.output(SP[0], False)
GPIO.output(SP[1], False)
GPIO.output(SP[2], True)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], False)
GPIO.output(SP[1], True)
GPIO.output(SP[2], True)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], False)
GPIO.output(SP[1], True)
GPIO.output(SP[2], False)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], True)
GPIO.output(SP[1], True)
GPIO.output(SP[2], False)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], True)
GPIO.output(SP[1], False)
GPIO.output(SP[2], False)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], True)
GPIO.output(SP[1], False)
GPIO.output(SP[2], False)
GPIO.output(SP[3], True)
time.sleep(0.001)

GPIO.output(18,True)
time.sleep(5)
GPIO.output(18,False)

for j in range(128):
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], True)
time.sleep(0.01)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], True)
GPIO.output(SPP[3], True)
time.sleep(0.001)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], True)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], True)
GPIO.output(SPP[2], True)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], True)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], True)
GPIO.output(SPP[1], True)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], True)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], False)
time.sleep(0.001)

GPIO.output(18,True)
time.sleep(5)
GPIO.output(18,False)

for k in range(128):
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], True)
time.sleep(0.01)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], True)
GPIO.output(SPPP[3], True)
time.sleep(0.001)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], True)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], True)
GPIO.output(SPPP[2], True)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], True)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], True)
GPIO.output(SPPP[1], True)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], True)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], False)
time.sleep(0.001)

GPIO.output(pin, False)

for pin in SPP:
GPIO.setup(pin,GPIO.OUT)
GPIO.output(pin, False)

for pin in SPPP:
GPIO.setup(pin,GPIO.OUT)
GPIO.output(pin,False)

GPIO.output(18,True)
time.sleep(5)
GPIO.output(18,False)

for i in range(128):
GPIO.output(SP[0], False)
GPIO.output(SP[1], False)
GPIO.output(SP[2], False)
GPIO.output(SP[3], True)
time.sleep(0.01)
GPIO.output(SP[0], False)
GPIO.output(SP[1], False)
GPIO.output(SP[2], True)
GPIO.output(SP[3], True)
time.sleep(0.001)
GPIO.output(SP[0], False)
GPIO.output(SP[1], False)
GPIO.output(SP[2], True)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], False)
GPIO.output(SP[1], True)
GPIO.output(SP[2], True)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], False)
GPIO.output(SP[1], True)
GPIO.output(SP[2], False)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], True)
GPIO.output(SP[1], True)
GPIO.output(SP[2], False)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], True)
GPIO.output(SP[1], False)
GPIO.output(SP[2], False)
GPIO.output(SP[3], False)
time.sleep(0.001)
GPIO.output(SP[0], True)
GPIO.output(SP[1], False)
GPIO.output(SP[2], False)
GPIO.output(SP[3], True)
time.sleep(0.001)

GPIO.output(18,True)
time.sleep(5)
GPIO.output(18,False)

for j in range(128):
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], True)
time.sleep(0.01)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], True)
GPIO.output(SPP[3], True)
time.sleep(0.001)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], True)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], True)
GPIO.output(SPP[2], True)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], False)
GPIO.output(SPP[1], True)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], True)
GPIO.output(SPP[1], True)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], False)
time.sleep(0.001)
GPIO.output(SPP[0], True)
GPIO.output(SPP[1], False)
GPIO.output(SPP[2], False)
GPIO.output(SPP[3], False)
time.sleep(0.001)

GPIO.output(18,True)
time.sleep(5)
GPIO.output(18,False)

for k in range(128):
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], True)
time.sleep(0.01)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], True)
GPIO.output(SPPP[3], True)
time.sleep(0.001)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], True)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], True)
GPIO.output(SPPP[2], True)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], False)
GPIO.output(SPPP[1], True)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], True)
GPIO.output(SPPP[1], True)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], False)
time.sleep(0.001)
GPIO.output(SPPP[0], True)
GPIO.output(SPPP[1], False)
GPIO.output(SPPP[2], False)
GPIO.output(SPPP[3], False)
time.sleep(0.001)